const products = [
  {id:'moss-mug',name:'Moss Study Mug',type:'Kitchen / Stoneware',price:34,category:'home',color:'#9aae82',bg:'#e2ead7',shape:'sphere',tilt:'-4deg',description:'A generous hand-thrown mug with a thumbprint handle and a quiet green glaze. Made for long mornings and second cups.'},
  {id:'orbit-lamp',name:'Orbit Table Lamp',type:'Objects / Lighting',price:128,category:'home',color:'#e57f61',bg:'#f4d4c7',shape:'sphere',tilt:'5deg',description:'A warm, portable glow in powder-coated steel. Orbit moves from bedside to desk without asking for a new mood.'},
  {id:'field-tote',name:'Field Note Tote',type:'Carry / Canvas',price:52,category:'carry',color:'#263c34',bg:'#c8d8ca',shape:'flat',tilt:'-3deg',description:'Heavyweight organic canvas, a deep outside pocket, and straps sized for a full day out.'},
  {id:'daily-cap',name:'Daily Cap / Ochre',type:'Wear / Cotton',price:38,category:'wear',color:'#d8a43d',bg:'#f3e6bd',shape:'flat',tilt:'4deg',description:'Six-panel cotton twill with a soft brim and an adjustable brass clasp.'},
  {id:'linen-throw',name:'Linen Throw / Chalk',type:'Home / Textile',price:96,category:'home',color:'#eee8d9',bg:'#d8e1df',shape:'flat',tilt:'-2deg',description:'Washed linen with a dry hand and just enough weight for the end of the sofa.'},
  {id:'utility-notebook',name:'Utility Notebook',type:'Paper / Stationery',price:18,category:'paper',color:'#e47d60',bg:'#f4d8cc',shape:'flat',tilt:'-7deg',description:'A ruled, lay-flat notebook with 160 pages of responsibly sourced paper.'},
  {id:'stone-tray',name:'Stone Catchall',type:'Home / Stoneware',price:42,category:'home',color:'#82928d',bg:'#d5ddda',shape:'flat',tilt:'2deg',description:'A small sculptural tray for keys, coins, and the things that find their way to the door.'},
  {id:'merino-scarf',name:'Merino Scarf / Ink',type:'Wear / Wool',price:74,category:'wear',color:'#293b43',bg:'#cbd8da',shape:'flat',tilt:'-4deg',description:'Fine merino wool, brushed once for softness and finished with a narrow raw edge.'}
];
let cart = JSON.parse(localStorage.getItem('northstar-cart') || '[]');
const app = document.querySelector('#app');
const money = value => `$${value.toFixed(2)}`;
const getProduct = id => products.find(product => product.id === id);
function productVisual(product, detail=false){return `<div class="${detail?'detail-image':'product-image'}" style="--product:${product.color};background:${product.bg}" ${detail?'':'data-shape="'+product.shape+'"'}></div>`}
function productCard(product){return `<article class="product-card" data-product="${product.id}">${productVisual(product)}<div class="product-meta"><div><div class="product-name">${product.name}</div><div class="product-type">${product.type}</div></div><div class="product-price">${money(product.price)}</div></div></article>`}
function home(){return `<section class="hero"><div class="hero-copy"><span class="eyebrow">Issue no. 04 / Objects for living</span><h1>Make room for the <em>good</em> stuff.</h1><p>Northstar is a considered collection of useful, beautiful things. Small-batch objects with a longer life in mind.</p><a class="primary-button" href="#shop" data-route="shop">Explore the collection <span>→</span></a></div><div class="hero-art" role="img" aria-label="Coral sculptural vessel against a pale blue background"></div></section><section class="section"><div class="section-heading"><div><span class="eyebrow">The current edit</span><h2>Things worth keeping</h2></div><a class="text-link" href="#shop" data-route="shop">View all objects</a></div><div class="product-grid">${products.slice(0,4).map(productCard).join('')}</div></section><section class="split-band"><div class="split-copy"><span class="eyebrow">The Northstar standard</span><h2>Less, but better considered.</h2><p>We choose makers who care about materials, process, and the years ahead.</p><a class="text-link" href="#about" data-route="about">Our approach →</a></div><div class="split-art"></div></section>`}
function shop(){return `<section class="section"><div class="section-heading"><div><span class="eyebrow">Browse the archive</span><h2>All objects</h2></div><span class="eyebrow" id="result-count">${products.length} objects</span></div><div class="shop-layout"><aside class="filter-panel"><h3>Filter by</h3><div class="filter-group"><span class="eyebrow">Category</span><label><input type="radio" name="category" value="all" checked> All objects</label><label><input type="radio" name="category" value="home"> Home</label><label><input type="radio" name="category" value="wear"> Wear</label><label><input type="radio" name="category" value="carry"> Carry</label><label><input type="radio" name="category" value="paper"> Paper</label></div><div class="filter-group"><span class="eyebrow">Price</span><label><input type="checkbox" id="under-60"> Under $60</label></div></aside><div><div class="shop-top"><strong id="shop-label">Showing all objects</strong><select class="select-control" id="sort-products" aria-label="Sort products"><option value="featured">Sort: Featured</option><option value="low">Price: Low to high</option><option value="high">Price: High to low</option></select></div><div class="product-grid" id="shop-grid">${products.map(productCard).join('')}</div></div></div></section>`}
function detail(id){const product=getProduct(id);return `<section class="product-detail"><div>${productVisual(product,true)}</div><div class="detail-copy"><span class="eyebrow">${product.type}</span><h1>${product.name}</h1><div class="detail-price">${money(product.price)}</div><p class="detail-description">${product.description}</p><div class="quantity-row"><div class="quantity"><button id="minus-qty" aria-label="Decrease quantity">−</button><span id="quantity">1</span><button id="plus-qty" aria-label="Increase quantity">+</button></div><button class="primary-button" id="add-to-bag">Add to bag <span>→</span></button></div><p class="eyebrow" style="margin-top:28px">Ships in 2–4 working days / carbon-neutral delivery</p></div></section>`}
function checkout(){const total=cart.reduce((sum,item)=>sum+getProduct(item.id).price*item.quantity,0);return `<section class="checkout-page"><span class="eyebrow">Northstar / secure checkout</span><h1>Almost yours.</h1><form class="checkout-form" id="checkout-form"><div class="form-section"><h2>Contact & delivery</h2><div class="field"><label for="email">Email address</label><input id="email" type="email" required placeholder="you@example.com"></div><div class="form-row"><div class="field"><label for="first-name">First name</label><input id="first-name" required></div><div class="field"><label for="last-name">Last name</label><input id="last-name" required></div></div><div class="field"><label for="address">Address</label><input id="address" required></div><div class="form-row"><div class="field"><label for="city">City</label><input id="city" required></div><div class="field"><label for="postcode">Postcode</label><input id="postcode" required></div></div><div class="field"><label for="card">Card number</label><input id="card" inputmode="numeric" minlength="12" required placeholder="4242 4242 4242 4242"></div><button class="primary-button full" type="submit">Place order <span>→</span></button></div><aside class="order-summary"><h2>Your order</h2>${cart.map(item=>`<div class="summary-line"><span>${getProduct(item.id).name} × ${item.quantity}</span><span>${money(getProduct(item.id).price*item.quantity)}</span></div>`).join('')}<div class="summary-total"><span>Total</span><span>${money(total)}</span></div><div class="field"><label for="promo">Promo code</label><input id="promo" placeholder="NORTHSTAR10"><button type="button" class="text-link" id="apply-promo" style="align-self:flex-start;margin-top:8px">Apply code</button><small id="promo-message"></small></div></aside></form></section>`}
function render(){const hash=location.hash.slice(1)||'home';const route=hash.startsWith('product/')?'detail':hash;app.innerHTML=route==='home'?home():route==='shop'?shop():route==='checkout'?checkout():route==='journal'?`<section class="journal-page"><span class="eyebrow">Field notes / 2026</span><h1>Ideas for a life well lived.</h1><div class="article-list"><article class="article"><span class="eyebrow">01 / Materials</span><div><h2>The honest beauty of useful things</h2><p>Why we are drawn to objects that reveal how they were made, rather than hide it.</p></div></article><article class="article"><span class="eyebrow">02 / Rituals</span><div><h2>A slower morning, by design</h2><p>The tiny cues that help a daily routine feel like something you chose.</p></div></article></div></section>`:route==='about'?`<section class="about-page"><span class="eyebrow">Our point of view</span><h1>Good design should make the everyday feel more like yours.</h1><p>Northstar is an independent objects studio based in the Pacific Northwest. We work with small makers to find things that are tactile, durable, and quietly distinctive.</p><div class="about-stat"><div><strong>28</strong><span>makers represented</span></div><div><strong>12</strong><span>countries shipped to</span></div><div><strong>100%</strong><span>considered</span></div></div></section>`:route==='detail'?detail(hash.split('/')[1]):checkout();bindRoute();updateCart();window.scrollTo(0,0)}
function bindRoute(){document.querySelectorAll('[data-product]').forEach(card=>card.addEventListener('click',()=>{location.hash=`product/${card.dataset.product}`}));document.querySelectorAll('[data-route]').forEach(link=>link.addEventListener('click',()=>{document.querySelectorAll('.main-nav a').forEach(nav=>nav.classList.toggle('active',nav.dataset.route===link.dataset.route))}));document.querySelectorAll('input[name="category"]').forEach(input=>input.addEventListener('change',filterShop));document.querySelector('#under-60')?.addEventListener('change',filterShop);document.querySelector('#sort-products')?.addEventListener('change',filterShop);document.querySelector('#add-to-bag')?.addEventListener('click',()=>{const id=location.hash.split('/')[1];const quantity=Number(document.querySelector('#quantity').textContent);const existing=cart.find(item=>item.id===id);if(existing)existing.quantity+=quantity;else cart.push({id,quantity});persist();showToast('Added to your bag');openCart()});document.querySelector('#plus-qty')?.addEventListener('click',()=>changeQuantity(1));document.querySelector('#minus-qty')?.addEventListener('click',()=>changeQuantity(-1));document.querySelector('#checkout-form')?.addEventListener('submit',placeOrder);document.querySelector('#apply-promo')?.addEventListener('click',()=>{const message=document.querySelector('#promo-message');message.textContent=document.querySelector('#promo').value.toUpperCase()==='NORTHSTAR10'?'Code applied: 10% off':'That code is not recognised';message.style.color=message.textContent.startsWith('Code')?'#587326':'#c04e39'})}
function changeQuantity(amount){const element=document.querySelector('#quantity');element.textContent=Math.max(1,Number(element.textContent)+amount)}
function filterShop(){const category=document.querySelector('input[name="category"]:checked')?.value||'all';const under=document.querySelector('#under-60')?.checked;const sort=document.querySelector('#sort-products')?.value||'featured';let visible=products.filter(product=>(category==='all'||product.category===category)&&(!under||product.price<60));if(sort==='low')visible.sort((a,b)=>a.price-b.price);if(sort==='high')visible.sort((a,b)=>b.price-a.price);document.querySelector('#shop-grid').innerHTML=visible.map(productCard).join('')||'<p class="empty-state">No objects match this edit.</p>';document.querySelector('#result-count').textContent=`${visible.length} objects`;document.querySelector('#shop-label').textContent=category==='all'?'Showing all objects':`Showing ${category}`;bindRoute()}
function persist(){localStorage.setItem('northstar-cart',JSON.stringify(cart));updateCart()}
function updateCart(){document.querySelector('#cart-count').textContent=cart.reduce((sum,item)=>sum+item.quantity,0);document.querySelector('#cart-total').textContent=money(cart.reduce((sum,item)=>sum+getProduct(item.id).price*item.quantity,0));document.querySelector('#cart-items').innerHTML=cart.length?cart.map(item=>{const product=getProduct(item.id);return `<div class="cart-item"><div class="cart-thumb" style="--product:${product.color}"></div><div><h3>${product.name}</h3><p>${item.quantity} × ${money(product.price)}</p><button class="remove-item" data-remove="${product.id}">Remove</button></div><strong>${money(product.price*item.quantity)}</strong></div>`}).join(''):'<p class="empty-state">Your bag is waiting for something good.</p>';document.querySelectorAll('[data-remove]').forEach(button=>button.addEventListener('click',()=>{cart=cart.filter(item=>item.id!==button.dataset.remove);persist()}))}
function openCart(){document.querySelector('#cart-drawer').classList.add('open');document.querySelector('#cart-drawer').setAttribute('aria-hidden','false');document.querySelector('#drawer-backdrop').classList.add('open')}
function closeCart(){document.querySelector('#cart-drawer').classList.remove('open');document.querySelector('#cart-drawer').setAttribute('aria-hidden','true');document.querySelector('#drawer-backdrop').classList.remove('open')}
function showToast(message){const toast=document.querySelector('#toast');toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2400)}
function placeOrder(event){event.preventDefault();if(!cart.length)return;cart=[];persist();app.innerHTML='<section class="order-success"><div class="success-mark">✳</div><span class="eyebrow">Order confirmed</span><h1>Thank you for choosing well.</h1><p>Your Northstar objects are on their way. A confirmation has been sent to your inbox.</p><a class="primary-button" href="#shop" data-route="shop" style="margin:25px auto;width:max-content">Continue browsing <span>→</span></a></section>';bindRoute()}
document.querySelector('#cart-toggle').addEventListener('click',openCart);document.querySelector('#cart-close').addEventListener('click',closeCart);document.querySelector('#drawer-backdrop').addEventListener('click',closeCart);document.querySelector('#checkout-button').addEventListener('click',()=>{if(cart.length){closeCart();location.hash='checkout'}else showToast('Your bag is empty')});document.querySelector('#search-toggle').addEventListener('click',()=>{const bar=document.querySelector('#search-bar');bar.hidden=!bar.hidden;if(!bar.hidden)document.querySelector('#search-input').focus()});document.querySelector('#search-input').addEventListener('input',event=>{const query=event.target.value.toLowerCase();if(location.hash!=='#shop')location.hash='shop';setTimeout(()=>{const grid=document.querySelector('#shop-grid');if(grid){const visible=products.filter(product=>`${product.name} ${product.type}`.toLowerCase().includes(query));grid.innerHTML=visible.map(productCard).join('')||'<p class="empty-state">No objects match your search.</p>';bindRoute()}},0)});document.querySelector('#clear-search').addEventListener('click',()=>{document.querySelector('#search-input').value='';document.querySelector('#search-input').dispatchEvent(new Event('input'))});window.addEventListener('hashchange',render);render();
